# This is a config for E2B sandbox template.
# You can use template ID (iy5zh0fbqjqiqp3cd0ra) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("iy5zh0fbqjqiqp3cd0ra") # Sync sandbox
# sandbox = await AsyncSandbox.create("iy5zh0fbqjqiqp3cd0ra") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('iy5zh0fbqjqiqp3cd0ra')

dockerfile = "e2b.Dockerfile"
template_id = "iy5zh0fbqjqiqp3cd0ra"
