# This is a config for E2B sandbox template.
# You can use template ID (hgqcvfyyr1oynxkopwcv) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("hgqcvfyyr1oynxkopwcv") # Sync sandbox
# sandbox = await AsyncSandbox.create("hgqcvfyyr1oynxkopwcv") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('hgqcvfyyr1oynxkopwcv')

dockerfile = "e2b.Dockerfile"
template_id = "hgqcvfyyr1oynxkopwcv"
template_name = "hello-world"
