# This is a config for E2B sandbox template.
# You can use template ID (zhlsrvvoeuzm9sb9rq8q) or template name (chat-interface) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("chat-interface") # Sync sandbox
# sandbox = await AsyncSandbox.create("chat-interface") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('chat-interface')

dockerfile = "e2b.Dockerfile"
template_name = "chat-interface"
template_id = "zhlsrvvoeuzm9sb9rq8q"
