# This is a config for E2B sandbox template.
# You can use template ID (ohrnldy7uf4t0970brlm) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("ohrnldy7uf4t0970brlm") # Sync sandbox
# sandbox = await AsyncSandbox.create("ohrnldy7uf4t0970brlm") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ohrnldy7uf4t0970brlm')

dockerfile = "e2b.Dockerfile"
template_id = "ohrnldy7uf4t0970brlm"
